### ISSUE TITLE
Q: How to implement continent endpoint?

### ISSUE THREAD

**Issue by Mikayex** [greaka/gw2lib#19]
How would you implement the [continent endpoint](https://wiki.guildwars2.com/wiki/API:2/continents) ?

Especially the [subresources](https://wiki.guildwars2.com/wiki/API:2/continents#Subresources) : they need multiple ids in the URL but the current traits only handle one id.

I think it needs some work to support that use case but i'm not confident enough to do a PR that implement that...

**Comment by TheMrMilchmann** [comment]
Ideally, a solution with support for an arbitrary amount of IDs is required. For `/v2/continents` you could get away with two IDs by supporting `/v2/continents/:id/floors` as that covers all information. (The fine-grained requests are only helpful if you want to save bandwidth, but, if that's a concern, you should probably preprocess the data anyway.)

However, there are additional endpoints that use multiple IDs. To name a few:
- `/v2/emblem/:type`
- `/v2/commerce/transactions/:relevance/:type`
- `/v2/pvp/seasons/:id/leaderboards/:board/:region`

**Comment by Mikayex** [comment]
Using a struct as id was my initial idea indeed... Wanted to see if another solution would be better.

I will try to do that then
